[package]
name = "actix_mysql"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "actix_mysql"

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt"] }

[dependencies]
# runtime
actix-web = "4.1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
mysql = "23.0.0"

# error handling
thiserror = "1.0.37"
anyhow = "1.0.65"
#serde
serde_json = "1"
serde = "1.0.147"
serde-aux = "3.1.0"
# tracing crates
tracing = {version = "0.1.35", features = ["log"]}
tracing-log = "0.1.3"
tracing-bunyan-formatter = "0.3.3"
tracing-subscriber = { version = "0.3.14", features = ["registry", "env-filter"] }
tracing-actix-web = "0.6.0"
# others
config = "0.13.2"
url = "2.2.2"
substring = "1.4.5"
secrecy = { version = "0.8.0", features = ["serde"] }
unicode-segmentation = "1.9.0"
claim = "0.5.0"

[dependencies.sqlx]
version = "0.6.0"
default-features = false
features = [
"runtime-actix-rustls",
"macros",
"mysql",
"uuid",
"chrono",
"migrate",
"offline"
]
