application:
  port: 8000
  # API KEY that used to validate the request on `/authenticate`
  api_key: "Bearer test123"
  
database:
  # name of the test database, this database will be droped and created when running the tests
  test_database_name: "TEST_RUST"
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "root"
  database_name: "test"
