application:
  port: 8000
  
database:
  # name of the test database, this database will be droped and created when running the tests
  # for safety, the program will panic if the database name does not contain the "TEST" string.
  test_database_name: "TEST_RUST"
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "root"
  database_name: "test"
