application:
  port: 8000
  api_key: "test123"
  
database:
  # name of the test database, this database will be droped and created when running the tests
  test_db_name: "TEST_RUST"
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "root"
  database_name: "test"
